FROM ubuntu:latest

RUN mkdir /app
WORKDIR /app

RUN apt-get update -y
RUN apt-get install -y \ 
    python3-pip python3-dev \
    build-essential libpq-dev

COPY requirements.txt /app/
RUN pip3 install -r requirements.txt

COPY . /app/

ENTRYPOINT ["/app/entrypoint.prod.sh"]
RUN ["chmod", "+x", "/app/entrypoint.prod.sh"]
